# https://malbiruk.github.io/driftwm/config.html
mod_key = "super"

focus_follows_mouse = true
window_placement = "center"

autostart = [ "waybar" , "mako", "~/nixos-dotfiles/dotfiles/wofi/scripts/wall restore"] 

[session]
restore_windows = false
restore_camera = false
[xwayland]
enabled = true

[navigation]
trackpad_speed = 1.5
mouse_speed = 1.0
drift = 0.15
camera_speed = 0.3
auto_navigate_on_close = true

[background]
#type = "wallpaper"
#path = "~/nixos-dotfiles/Wallpapers/clouds.jpg"
type = "none"

[decorations]
corner_radius = 0
shadow = false
default_mode = "minimal"
opacity = 1.0
blur = false

[snap]
enabled = false


[keybindings]
"mod+t" = "spawn kitty"
"mod+return" = "spawn wofi"
"mod+tab" = "spawn firefox"
"mod+shift+s" = "exec grim -g \"$(slurp)\" - | wl-copy"

"mod+k" = "spawn ~/nixos-dotfiles/dotfiles/wofi/scripts/sys"
"mod+o" = "spawn ~/nixos-dotfiles/dotfiles/wofi/scripts/wall"
"mod+l" = "spawn ~/nixos-dotfiles/dotfiles/wofi/scripts/calc"

"mod+q" = "close-window"
"mod+f" = "toggle-fullscreen"
"mod+m" = "fit-window"
"mod+c" = "center-window"

"mod+w" = "center-nearest up"
"mod+s" = "center-nearest down"
"mod+a" = "center-nearest left"
"mod+d" = "center-nearest right"

"mod+ctrl+w" = "nudge-window up"
"mod+ctrl+s" = "nudge-window down"
"mod+ctrl+a" = "nudge-window left"
"mod+ctrl+d" = "nudge-window right"

"mod+1" = "go-to-bookmark 1"
"mod+2" = "go-to-bookmark 2"
"mod+3" = "go-to-bookmark 3"
"mod+4" = "go-to-bookmark 4"

"mod+shift+1" = "set-bookmark 1"
"mod+shift+2" = "set-bookmark 2"
"mod+shift+3" = "set-bookmark 3"
"mod+shift+4" = "set-bookmark 4"

"XF86AudioPlay" = "spawn playerctl play-pause"
"XF86AudioNext" = "spawn playerctl next"
"XF86AudioPrev" = "spawn playerctl previous"

"mod+ctrl+shift+q" = "quit"

[mouse.on-window]

"mod+left" = "move-window"
"mod+right" = "resize-window"

[[outputs]]
name = "DP-2"
transform = "90"
position = [0, -1595]
mode = "3440x1440"
focus_placement = "left"

[[outputs]]
name = "DP-3"
mode = "3440x1440@100"
