"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bg0)\
$os\
[](bg:bg1 fg:bg0)\
$directory\
[](bg:bg2 fg:bg0)\
$git_branch$git_status\
[](bg:bg3 fg:bg2)\
$nix_shell\
[](fg:bg3)\
$fill\
[](fg:bg0)\
$cmd_duration\
[](fg:bg0)\
$time\
[ ](fg:bg0)
$character"""

add_newline = true
palette = "wal"

[fill]
symbol = " "

[os]
disabled = false
style = "bg:bg0 fg:fg"
format = "[ $symbol ]($style)"

[os.symbols]
NixOS = "󱄅"
Linux = ""
Windows = ""
Macos = ""

[nix_shell]
disabled = false
style = "bg:bg3 fg:bg0"
symbol = "❄️"
format = "[ $symbol$state ]($style)"
impure_msg = "impure"
pure_msg = "pure"

[directory]
style = "bg:bg1 fg:bg0"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[git_branch]
style = "bg:bg2 fg:bg0"
symbol = ""
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:bg2 fg:bg0"
format = '[($all_status$ahead_behind )]($style)'

[cmd_duration]
style = "bg:bg2 fg:bg0"
format = "[  $duration ]($style)"
min_time = 500

[time]
disabled = false
style = "bg:bg1 fg:bg0"
format = "[  $time ]($style)"
time_format = "%H:%M"

[character]
success_symbol = "[❯](bold fg:accent)"
error_symbol = "[❯](bold #ff6b6b)"
vimcmd_symbol = "[❮](bold fg:accent)"

[package]
disabled = true

[username]
style_user = "bg:bg0 fg:fg"
style_root = "bg:bg0 fg:#ff6b6b"
format = "[ $user ]($style)"
disabled = true
show_always = false

[hostname]
ssh_only = true
style = "bg:bg0 fg:fg"
format = "[ $hostname ]($style)"
disabled = true


# >>> wal palette >>>
[palettes.wal]
bg0 = "#042912"
bg1 = "#339b56"
bg2 = "#90e3ab"
bg3 = "#90e3ab"
fg = "#c2c7c4"
accent = "#78e5e7"
# <<< wal palette <<<
